blank_issues_enabled: true
contact_links:
  - name: New Causal Case Study
    url: https://github.com/DigitalCausalityLab/issues/new
    about: Add a new case study which can serve as an inspiration of a new data product on causality.